name: CI
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hustcer/setup-moonbit@v1
      - run: moon check --deny-warn
      - run: moon test
      - run: moon check --target wasm
      - run: moon package --list
